### ISSUE TITLE
Carousel!

### ISSUE THREAD

**Issue by juliastarkov** [juliastarkov/juliastarkov.github.io#10]
Here are the sample images:
![home](https://user-images.githubusercontent.com/26334275/43042136-19804ac0-8d2a-11e8-8959-14199b51cf01.jpg)
![data stories visual](https://user-images.githubusercontent.com/26334275/43042138-1db4df70-8d2a-11e8-9cc7-f1ea0a395f82.jpg)
![arrest rates](https://user-images.githubusercontent.com/26334275/43042139-23b33d72-8d2a-11e8-9e0d-6a1afa655c51.jpg)

**Comment by JacobWylie** [comment]
refer to issue #8 [https://github.com/juliastarkov/juliastarkov.github.io/issues/8](url)
