### ISSUE TITLE
Decorative icon removal

### ISSUE THREAD

**Issue by juliastarkov** [juliastarkov/juliastarkov.github.io#12]
Please remove (or push down) the decorative icons I've selected with the red circles. 
<img width="947" alt="screen shot 2018-07-21 at 9 10 18 pm" src="https://user-images.githubusercontent.com/26334275/43042165-dd65143e-8d2a-11e8-9911-4aef180fe90b.png">
<img width="869" alt="screen shot 2018-07-21 at 9 12 02 pm" src="https://user-images.githubusercontent.com/26334275/43042166-e13f2bd0-8d2a-11e8-9924-d5dffefefb65.png">

**Comment by JacobWylie** [comment]
moved the first three icons down. removed the fourth
