### ISSUE TITLE
Contact Visual Updates

### ISSUE THREAD

**Issue by juliastarkov** [juliastarkov/juliastarkov.github.io#3]
![contact specs](https://user-images.githubusercontent.com/26334275/42425909-bc9a90d8-82d7-11e8-9350-bd5aa88e4334.png)

Please see the above to make changes to the visuals on the contact form @JacobWylie

**Comment by juliastarkov** [comment]
![contact specs](https://user-images.githubusercontent.com/26334275/43042115-81296176-8d29-11e8-8ab8-44aa517f2a6d.png)

Overlay of mockups vs current

**Comment by JacobWylie** [comment]
I just double checked all of the dimensions and they are exactly the same as the mockup. Not really sure what you are looking at. Should be easy enough for you to adjust it.
