### ISSUE TITLE
Text Styles

### ISSUE THREAD

**Issue by juliastarkov** [juliastarkov/juliastarkov.github.io#7]
Please set these two up:

Quote Style: Italicized, Karla, Bold
Bullet Point Style: Indented 10 px, small 4A4A4A circle bullet

Put them anywhere and let me know and i can copy and paste

**Comment by JacobWylie** [comment]
add class "bullet-point" to an element
example: <li class="bullet-point">I was the sole researcher and designer working with four developers and a content strategist</li>

add class "quote-text" to an element. a <span> element will work best for specific text or add it to an entire element to quote all of the text.
example: I was the sole researcher <span class="quote-text">and designer working with four developers</span> and a content strategist
