### ISSUE TITLE
Extra Wireframe/etc pages

### ISSUE THREAD

**Issue by juliastarkov** [juliastarkov/juliastarkov.github.io#9]
Please set up a way I can display pages to link from the case studies. It can be 2 in a row on desktop and 1 in a row on mobile. Let me know if you need mockups.

**Comment by JacobWylie** [comment]
I don't understand this. Please provide a mockup and more detailed information.

**Comment by juliastarkov** [comment]
I just need a blank page that I can add images of wire frames to (and one I can copy to create more pages in the future):
<img width="1680" alt="screen shot 2018-08-26 at 2 48 14 pm" src="https://user-images.githubusercontent.com/26334275/44633348-1bd86380-a93f-11e8-843c-1266d4e623d6.png">
